### ISSUE TITLE
fzf: Unable to fetch URL from any source

### ISSUE THREAD

**Issue by abdomit** [MicroTCA-Tech-Lab/meta-techlab-utils#5]
I am a complete beginner with bitbake, please forgive me if I say something irrelevant.

I experienced the following error:

```
ERROR: fzf-0.29.0-r0 do_fetch: Fetcher failure: Unable to find revision 2c746f29c263bb7437b6b4870e577335eb4871e1 in branch master even from upstream
ERROR: fzf-0.29.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/saracen/walker;protocol=https;name=go-walker;destsuffix=fzf-0.29.0/src/github.com/saracen/walker'. Unable to fetch U
RL from any source.
```

If I understand correctly, the issue is that the repository github.com/saracen/walker renamed its branch `master` to `main`.

It seems that I could fix this issue by changing the correct line in `recipes-shells/fzf/fzf_0.29.0.bb` with:

```
git://github.com/saracen/walker;protocol=https;branch=main;name=go-walker;destsuffix=${BPN}-${PV}/src/github.com/saracen/walker \
```

edit: I am using the branch rel-v2020.2, I saw that this issue with `fzf` was corrected in the more recent branches.

**Comment by patrislav1** [comment]
We sometimes don't notice link rot like this, since we're using a local download mirror ...
You're welcome to do a PR for this fix.
